-- File generated by the BNF Converter (bnfc 2.9.4).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module Latte.SkelLatte where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified Latte.AbsLatte

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: Latte.AbsLatte.Ident -> Result
transIdent x = case x of
  Latte.AbsLatte.Ident string -> failure x

transProgram :: Show a => Latte.AbsLatte.Program' a -> Result
transProgram x = case x of
  Latte.AbsLatte.Prog _ stmts -> failure x

transStmt :: Show a => Latte.AbsLatte.Stmt' a -> Result
transStmt x = case x of
  Latte.AbsLatte.Empty _ -> failure x
  Latte.AbsLatte.Exp _ expr -> failure x
  Latte.AbsLatte.Ass _ idents expr -> failure x
  Latte.AbsLatte.AssAdd _ ident expr -> failure x
  Latte.AbsLatte.AssSub _ ident expr -> failure x
  Latte.AbsLatte.AssMul _ ident expr -> failure x
  Latte.AbsLatte.AssDiv _ ident expr -> failure x
  Latte.AbsLatte.AssMod _ ident expr -> failure x
  Latte.AbsLatte.Incr _ ident -> failure x
  Latte.AbsLatte.Decr _ ident -> failure x
  Latte.AbsLatte.Ret _ expr -> failure x
  Latte.AbsLatte.Print _ expr -> failure x
  Latte.AbsLatte.PrintLn _ expr -> failure x
  Latte.AbsLatte.Assert _ expr -> failure x
  Latte.AbsLatte.If _ expr block -> failure x
  Latte.AbsLatte.IfElse _ expr block1 block2 -> failure x
  Latte.AbsLatte.While _ expr block -> failure x
  Latte.AbsLatte.Brk _ -> failure x
  Latte.AbsLatte.Cntn _ -> failure x
  Latte.AbsLatte.BStmt _ block -> failure x
  Latte.AbsLatte.Decl _ type_ items -> failure x
  Latte.AbsLatte.FnDef _ type_ ident pars block -> failure x

transBlock :: Show a => Latte.AbsLatte.Block' a -> Result
transBlock x = case x of
  Latte.AbsLatte.Blck _ stmts -> failure x

transItem :: Show a => Latte.AbsLatte.Item' a -> Result
transItem x = case x of
  Latte.AbsLatte.NoInit _ ident -> failure x
  Latte.AbsLatte.Init _ ident expr -> failure x

transPar :: Show a => Latte.AbsLatte.Par' a -> Result
transPar x = case x of
  Latte.AbsLatte.ParVal _ type_ ident -> failure x
  Latte.AbsLatte.ParRef _ type_ ident -> failure x

transType :: Show a => Latte.AbsLatte.Type' a -> Result
transType x = case x of
  Latte.AbsLatte.Int _ -> failure x
  Latte.AbsLatte.Str _ -> failure x
  Latte.AbsLatte.Bool _ -> failure x
  Latte.AbsLatte.Tuple _ types -> failure x

transExpr :: Show a => Latte.AbsLatte.Expr' a -> Result
transExpr x = case x of
  Latte.AbsLatte.EOr _ expr1 expr2 -> failure x
  Latte.AbsLatte.EAnd _ expr1 expr2 -> failure x
  Latte.AbsLatte.ERel _ expr1 relop expr2 -> failure x
  Latte.AbsLatte.EAdd _ expr1 addop expr2 -> failure x
  Latte.AbsLatte.EMul _ expr1 mulop expr2 -> failure x
  Latte.AbsLatte.Not _ expr -> failure x
  Latte.AbsLatte.Neg _ expr -> failure x
  Latte.AbsLatte.EVar _ ident -> failure x
  Latte.AbsLatte.EInt _ integer -> failure x
  Latte.AbsLatte.EString _ string -> failure x
  Latte.AbsLatte.ETrue _ -> failure x
  Latte.AbsLatte.EFalse _ -> failure x
  Latte.AbsLatte.ETuple _ exprs -> failure x
  Latte.AbsLatte.EApp _ ident args -> failure x

transArg :: Show a => Latte.AbsLatte.Arg' a -> Result
transArg x = case x of
  Latte.AbsLatte.ValArg _ expr -> failure x
  Latte.AbsLatte.RefArg _ ident -> failure x

transAddOp :: Show a => Latte.AbsLatte.AddOp' a -> Result
transAddOp x = case x of
  Latte.AbsLatte.Plus _ -> failure x
  Latte.AbsLatte.Minus _ -> failure x

transMulOp :: Show a => Latte.AbsLatte.MulOp' a -> Result
transMulOp x = case x of
  Latte.AbsLatte.Times _ -> failure x
  Latte.AbsLatte.Div _ -> failure x
  Latte.AbsLatte.Mod _ -> failure x

transRelOp :: Show a => Latte.AbsLatte.RelOp' a -> Result
transRelOp x = case x of
  Latte.AbsLatte.LTH _ -> failure x
  Latte.AbsLatte.LE _ -> failure x
  Latte.AbsLatte.GTH _ -> failure x
  Latte.AbsLatte.GE _ -> failure x
  Latte.AbsLatte.EQU _ -> failure x
  Latte.AbsLatte.NE _ -> failure x
